name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run test in testim
      run: docker run 5035/testimdemo1 --token "k96WmRtVnO2tQL3DzBpETWlT9CtATfLdVpPxqsPWgcItIX60tI"  --project "sVFVz4Wvezd6ayvGkBDD" --grid "Testim-Grid" -r /opt/testim-runner/testim-sanity-12-report.xml 
